workflows:
  - ".github/workflows/lint-*"
  - ".github/workflows/scan-*"

github:
  - ".github/*.yml"
  - ".github/fixtures/*"
  - ".github/workflows/internal-*"

docs:
  - "**/*.md"

chore:
  - "Makefile"
  - "VERSION"
  - ".gitignore"
  - ".markdownlint.yml"
  - ".yamllint.yml"
