workflows:
  - ".github/workflows/lint-*"

github:
  - ".github/**/*"
  - "!.github/workflows/*"
  - ".github/workflows/internal-*"

docs:
  - "**/*.md"

chore:
  - "Makefile"
  - "VERSION"
  - ".gitignore"
  - ".markdownlint.yml"
  - ".yamllint.yml"
