name: Internal Test
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/internal-test.yml"
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
      - "**.md"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    uses: ./.github/workflows/lint-yaml.yml

  lint-markdown:
    uses: ./.github/workflows/lint-markdown.yml

  lint-markdown-with-config:
    uses: ./.github/workflows/lint-markdown.yml
    with:
      markdownlint-config: ".markdownlint.yml"

  lint-action:
    uses: ./.github/workflows/lint-action.yml
    with:
      actionlint-ignore-options: >
        "permissions" section should not be empty.
