name: Test for internal
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/internal-test.yml"
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
      - "**.md"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    uses: ./.github/workflows/lint-yaml.yml

  lint-markdown:
    uses: ./.github/workflows/lint-markdown.yml

  lint-action:
    uses: ./.github/workflows/lint-action.yml
