name: Internal Test
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/internal-test.yml"
  pull_request:
    paths:
      - "**.yml"
      - "**.yaml"
      - "**.md"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    uses: ./.github/workflows/lint-yaml.yml

  lint-yaml-with-inputs:
    uses: ./.github/workflows/lint-yaml.yml
    with:
      yamllint-config: ".yamllint.yml"
      timeout-minutes: 3

  lint-markdown:
    uses: ./.github/workflows/lint-markdown.yml

  lint-markdown-with-inputs:
    uses: ./.github/workflows/lint-markdown.yml
    with:
      markdownlint-config: ".markdownlint.yml"
      timeout-minutes: 3

  lint-shell:
    uses: ./.github/workflows/lint-shell.yml

  lint-shell-with-inputs:
    uses: ./.github/workflows/lint-shell.yml
    with:
      timeout-minutes: 3

  lint-action:
    uses: ./.github/workflows/lint-action.yml
    with:
      actionlint-ignore-options: >
        "permissions" section should not be empty.

  lint-action-with-inputs:
    uses: ./.github/workflows/lint-action.yml
    with:
      actionlint-ignore-options: '"permissions" section should not be empty.'
      timeout-minutes: 3
