name: Internal Test
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/internal-test.yml"
  pull_request:
    paths:
      - ".github/workflows/lint-*.yml"
      - ".github/workflows/scan-*.yml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BASE_BRANCH: "main"
    outputs:
      lint-yaml: ${{ steps.git-diff.outputs.lint-yaml }}
      lint-markdown: ${{ steps.git-diff.outputs.lint-markdown }}
      lint-shell: ${{ steps.git-diff.outputs.lint-shell }}
      lint-action: ${{ steps.git-diff.outputs.lint-action }}
      scan-secret: ${{ steps.git-diff.outputs.scan-secret }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Git diff
        id: git-diff
        run: |
          git fetch --no-tags --no-recurse-submodules --depth=1 origin "${BASE_BRANCH}"
          files="$(git diff origin/"${BASE_BRANCH}" --name-only)"
          echo "::set-output name=lint-yaml::$(echo "${files}" | grep "lint-yaml" || true)"
          echo "::set-output name=lint-markdown::$(echo "${files}" | grep "lint-markdown" || true)"
          echo "::set-output name=lint-shell::$(echo "${files}" | grep "lint-shell" || true)"
          echo "::set-output name=lint-action::$(echo "${files}" | grep "lint-action" || true)"
          echo "::set-output name=scan-secret::$(echo "${files}" | grep "scan-secret" || true)"

  lint-yaml:
    uses: ./.github/workflows/lint-yaml.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-yaml }}

  lint-yaml-with-inputs:
    uses: ./.github/workflows/lint-yaml.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-yaml }}
    with:
      yamllint-config: ".yamllint.yml"
      timeout-minutes: 3

  lint-markdown:
    uses: ./.github/workflows/lint-markdown.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-markdown }}

  lint-markdown-with-inputs:
    uses: ./.github/workflows/lint-markdown.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-markdown }}
    with:
      markdownlint-config: ".markdownlint.yml"
      timeout-minutes: 3

  lint-shell:
    uses: ./.github/workflows/lint-shell.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-shell }}

  lint-shell-with-inputs:
    uses: ./.github/workflows/lint-shell.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-shell }}
    with:
      timeout-minutes: 3

  lint-action:
    uses: ./.github/workflows/lint-action.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-action }}
    with:
      actionlint-ignore-options: >
        "permissions" section should not be empty.

  lint-action-with-inputs:
    uses: ./.github/workflows/lint-action.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.lint-action }}
    with:
      actionlint-ignore-options: '"permissions" section should not be empty.'
      timeout-minutes: 3

  scan-secret:
    uses: ./.github/workflows/scan-secret.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.scan-secret }}

  scan-secret-with-inputs:
    uses: ./.github/workflows/scan-secret.yml
    needs: [diff]
    if: ${{ needs.diff.outputs.scan-secret }}
    with:
      timeout-minutes: 3
