name: Lint Markdown
on:
  workflow_call:
    inputs:
      markdownlint-config:
        default: ""
        required: false
        type: string
        description: "Path to a configuration file."
      timeout-minutes:
        default: 5
        required: false
        type: number
        description: "The maximum number of minutes to let a job run before GitHub automatically cancels it."

jobs:
  markdownlint:
    name: Lint by markdownlint
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Display markdownlint
        run: markdownlint --version
      - name: Run markdownlint
        env:
          CONFIG: ${{ inputs.markdownlint-config }}
        run: |
          declare -a args=("--dot")
          if [[ "${CONFIG}" != "" ]]; then
            args+=("--config")
            args+=("${CONFIG}")
          fi
          markdownlint "${args[@]}" '**/*.md'

  prettier:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format check with Prettier
        uses: tmknom/prettier-action@v0
        with:
          parser: "markdown"
