name: Lint YAML
on:
  workflow_call:
    inputs:
      yamllint-config:
        default: ""
        required: false
        type: string
        description: "Path to a configuration file."
      timeout-minutes:
        default: 5
        required: false
        type: number
        description: "The maximum number of minutes to let a job run before GitHub automatically cancels it."

jobs:
  yamllint:
    # use pre-installed yamllint
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
    name: Lint by yamllint
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Display yamllint
        run: yamllint --version
      - name: Run yamllint
        env:
          CONFIG: ${{ inputs.yamllint-config }}
        run: |
          declare -a args=("--strict" "--format" "github")
          if [[ "${CONFIG}" != "" ]]; then
            args+=("--config-file")
            args+=("${CONFIG}")
          fi
          yamllint "${args[@]}" .

  prettier:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format check with Prettier
        uses: tmknom/prettier-action@v0
        with:
          parser: "yaml"
