name: Lint Action
on:
  workflow_call:
    inputs:
      actionlint-ignore-options:
        default: ""
        required: false
        type: string
        description: >
          Regular expression matching to error messages you want to ignore for actionlint.
          Specify on multiple lines, you can set repeatable ignore flags.

jobs:
  actionlint:
    name: Lint by actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Display actionlint
        run: ./actionlint --version
      - name: Run actionlint
        env:
          IGNORE_OPTIONS: ${{ inputs.actionlint-ignore-options }}
        run: |
          IFS=$'\n' read -ra ignore_option_array <<< "$(printenv IGNORE_OPTIONS)"

          declare -a options=()
          for ignore_option in "${ignore_option_array[@]}"; do
            options+=("-ignore")
            options+=("${ignore_option}")
          done

          ./actionlint "${options[@]}"
