name: Lint Markdown
on:
  workflow_call:
    inputs:
      markdownlint-config:
        default: ""
        required: false
        type: string
        description: "Path to a configuration file."

jobs:
  markdownlint:
    name: Lint by markdownlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Display markdownlint
        run: markdownlint --version
      - name: Run markdownlint
        env:
          MARKDOWNLINT_CONFIG: ${{ inputs.markdownlint-config }}
        run: |
          declare -a args=("--dot")
          if [[ "${MARKDOWNLINT_CONFIG}" != "" ]]; then
            args+=("--config")
            args+=("${MARKDOWNLINT_CONFIG}")
          fi
          markdownlint "${args[@]}" '**/*.md'

  prettier:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Format check with Prettier
        uses: tmknom/prettier-action@v0
        with:
          parser: "markdown"
