name: Scan Secret
on:
  workflow_call:
    inputs:
      timeout-minutes:
        default: 5
        required: false
        type: number
        description: "The maximum number of minutes to let a job run before GitHub automatically cancels it."

jobs:
  secretlint:
    name: Scan by secretlint
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull secretlint
        run: |
          docker pull secretlint/secretlint
      - name: Display secretlint
        run: |
          docker run --rm --security-opt=no-new-privileges --cap-drop all --network none \
          secretlint/secretlint --version
      - name: Run secretlint
        run: |
          docker run --rm -v "$(pwd)":/work -w /work \
          --security-opt=no-new-privileges --cap-drop all --network none \
          secretlint/secretlint secretlint --maskSecrets '**/*'
